language: bash

sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t ecmi/mc:prod .
  - docker tag -f ecmi/mc:prod docker.io/ecmi/mc:prod
  - docker push docker.io/ecmi/mc:prod
