language: bash

sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t ecmi/ers:prod .
  - docker tag -f ecmi/ers:prod docker.io/ecmi/ers:prod
  - docker push ecmi/ers:prod
